using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Zatca_CSID.Models
{
        public class _ZInvoice
    {
        public string ID { get; set; }
        public string IssueDate { get; set; }
        public string IssueTime { get; set; }
        public int InvoiceTypeCode { get; set; }
        public string InvoiceTypeCodeName { get; set; }
        public string Cur_Code { get; set; }
        public string Tax_Cur_Code { get; set; }
        public string Doc_Ref_ID { get; set; }
        public int Adtl_Ref_UUID { get; set; } = 0;
        public string Adtl_Ref_ICV { get; set; }
        public string Bill_ref { get; set; }
        public string DeliveryDate { get; set; }
        public string Actual_DeliveryDate { get; set; }
        public string PaymentMeansCode { get; set; }
        public string PaymentNotes { get; set; }

        public _AllowanceCharge allowancecharge = new _AllowanceCharge();
        public IList<_InvoiceLine> invline = new List<_InvoiceLine>();
        public _SupCustInfo supplier = new _SupCustInfo();
        public _SupCustInfo customer = new _SupCustInfo();
        public AuthKey authKey = new AuthKey();

    }
        public class _SupCustInfo
    {
        public string ID { get; set; }
        public string SchemaID { get; set; }
        public string StreeName { get; set; }
        public string Building_Num { get; set; }
        public string PlotNum { get; set; }

        public string City { get; set; }
        public string Pincode { get; set; }
        public string SubDivision { get; set; }
        public string Country { get; set; }
        public string RegistrationName { get; set; }
        public string TaxID { get; set; }

    }
        public class _InvoiceLine
        {
            public decimal Qty { get; set; } = 0;
            public string Tax_ID { get; set; } = string.Empty;
            public decimal Taxper { get; set; } = 0;
            public bool ExcludeVat { get; set; } = false;
            public string ItemName { get; set; } = string.Empty;
            public Decimal Price { get; set; } = 0;
            public decimal Discount_Amt { get; set; } = 0;
            public string Discount_Reason { get; set; } = string.Empty;
            public string Tax_Excempt_reason { get; set; } = string.Empty;
            public string Tax_Excempt_ReasonCode { get; set; } = string.Empty;

        }
        public class AuthKey
        {
            public string Cer = string.Empty;
            public string Key = string.Empty;
            public string Pih = string.Empty;
        }
        public class EncodedInvoiceModel
    {
        /// <summary> Generated by CSID  </summary>
        public string Cer { get; set; } = string.Empty;
        /// <summary> Zatca OTP </summary>
        public string OTP { get; set; } = string.Empty;

        /// <summary> 388 (For Standard); 383 ( For DebitNote); 381 (For CreditNote); </summary>
        public int InvoiceTypeCode { get; set; } = 0;
        //       public string InvoiceTypeCodeName { get; set; } = string.Empty;

        /// <summary> Encoded Invoice  </summary>
        public string EncodedInvoice { get; set; }
        /// <summary> New HASH  </summary>
        public string InvoiceHash { get; set; } = string.Empty;
        /// <summary> UUID  </summary>
        public string UUID { get; set; } = string.Empty;
        /// <summary> IF true Production else UAT </summary>
        public bool IsProduction { get; set; } = false;
    }
        public class _AllowanceCharge
        {

            public string ID { get; set; } = string.Empty;
            public decimal MultiplierFactorNumeric { get; set; } = 0;
            public decimal Amount { get; set; } = 0;
            public decimal BaseAmount { get; set; } = 0;
            public bool ChargeIndicator { get; set; } = false;

            public string TaxID { get; set; } = string.Empty;

            public decimal Percent { get; set; } = 0;

            public string TaxExemptionReason { get; set; } = string.Empty;

            public string TaxExemptionReasonCode { get; set; } = string.Empty;

            public string AllowanceChargeReason { get; set; } = string.Empty;
         
        }
}
